// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr9C_31pBqzUk0gTfWDoGtl3a8KNJwPg4',
    appId: '1:943772556864:web:50bda125cf57217a4709a5',
    messagingSenderId: '943772556864',
    projectId: 'cart-70210',
    authDomain: 'cart-70210.firebaseapp.com',
    storageBucket: 'cart-70210.firebasestorage.app',
    measurementId: 'G-Q34T1MN24K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTZ-RyLdE0KmSN5ZHaAu7lri0iDpn5Tu8',
    appId: '1:943772556864:android:96f276bb61e157b64709a5',
    messagingSenderId: '943772556864',
    projectId: 'cart-70210',
    storageBucket: 'cart-70210.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByLLtU13xDUw4Uhoyi2RiWzmzcd9n7VKI',
    appId: '1:943772556864:ios:0bd8253b5503fc734709a5',
    messagingSenderId: '943772556864',
    projectId: 'cart-70210',
    storageBucket: 'cart-70210.firebasestorage.app',
    iosBundleId: 'com.example.nutrifix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByLLtU13xDUw4Uhoyi2RiWzmzcd9n7VKI',
    appId: '1:943772556864:ios:0bd8253b5503fc734709a5',
    messagingSenderId: '943772556864',
    projectId: 'cart-70210',
    storageBucket: 'cart-70210.firebasestorage.app',
    iosBundleId: 'com.example.nutrifix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr9C_31pBqzUk0gTfWDoGtl3a8KNJwPg4',
    appId: '1:943772556864:web:d2151796b7fd1edb4709a5',
    messagingSenderId: '943772556864',
    projectId: 'cart-70210',
    authDomain: 'cart-70210.firebaseapp.com',
    storageBucket: 'cart-70210.firebasestorage.app',
    measurementId: 'G-NDY8KP39CG',
  );
}
